---
- hosts: all
  become: yes
  tasks:
  - name: Install Nginx
    yum:
      name: nginx
      state: present
      update_cache: yes
    when: ansible_os_family == "RedHat"

  - name: Copy index.html
    copy:
      src: ../web_application/
      dest: /var/www/html/
      owner: nginx
      group: nginx
      mode: '0644'
      recursive: yes
