---
- hosts: all
  become: yes
  tasks:
  - name: Install Nginx
    apt:
      name: nginx
      state: present
      update_cache: yes
    when: ansible_os_family == "Debian"

  - name: Copy index.html
    copy:
      src: ../web_application/
      dest: /var/www/html/
      owner: www-data
      group: www-data
      mode: '0644'
      recursive: yes
